services:
  spark-master:
    image: docker.io/apache/spark:3.4.4
    container_name: spark-master
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./data:/opt/data
      - ./checkpoints:/opt/checkpoints
      - ./spark/app:/opt/spark-app
    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.master.Master
      - --host
      - spark-master
      - --port
      - "7077"
      - --webui-port
      - "8080"

  spark-worker:
    image: docker.io/apache/spark:3.4.4
    container_name: spark-worker
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ./data:/opt/data
      - ./checkpoints:/opt/checkpoints
      - ./spark/app:/opt/spark-app
    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.worker.Worker
      - spark://spark-master:7077
      - --webui-port
      - "8081"
      - --memory
      - "2G"
      - --cores
      - "2"

  spark-runner:
    image: docker.io/apache/spark:3.4.4
    container_name: spark-runner
    depends_on:
      - spark-master
      - spark-worker
    volumes:
      - ./data:/opt/data
      - ./checkpoints:/opt/checkpoints
      - ./spark/app:/opt/spark-app
      - ./jars:/opt/jars
    entrypoint: ["/opt/spark/bin/spark-submit"]
    command:
      - --jars
      - /opt/jars/clickhouse-jdbc-all-0.9.6.jar
      - --master
      - spark://spark-master:7077
      - --deploy-mode
      - client
      - /opt/spark-app/main.py
  
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin123
      - CLICKHOUSE_DB=default
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: social-api
    depends_on:
      - clickhouse
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=9000
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin123
      - CLICKHOUSE_DATABASE=default
    ports:
      - "8000:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  clickhouse_data:
